# Source:
#
# This file is used to configure the GitHub Issue Template.

# README
readme: true

# Blank Issues
blank_issues_enabled: false

# Issue Forms
issue_forms_enabled: true
issue_template: true  # Set to true to enable issue templates
issue_template_files:  # Specify the path to the issue templates
  - .github/ISSUE_TEMPLATE/bug_report.yml
  - .github/ISSUE_TEMPLATE/feature_request.yml

# Pull Request Forms
pull_request_forms_enabled: true
pull_request_template: true  # Set to true to enable pull request templates
pull_request_template_files:  # Specify the path to the pull request templates
  - .github/PULL_REQUEST_TEMPLATE.yml

# Contact Links
contact_links_enabled: true
contact_links:
  - name: GitHub Community Support
    url: https://discord.gg/psUyXF5hqq
    about: Please ask and answer questions in our Support Server.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
