name: Feature Request
description: Suggest a new feature
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees:
  - Ghostridr
  - Triage
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting a feature request! Please fill out the details below.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: "ex. Email: [User_Name](mailto:email@example.com)"
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the new feature you are suggesting.
      placeholder: |
        Please provide a clear and concise description of the feature.
        Include any relevant links or resources.
        If you are suggesting a new command, please include the command name and any relevant arguments.
        You could use:
        - For example: "I'm always frustrated when [...] so I'd like to see [...]"
        - For example: "I'd like to see a new command called [...]" that does [...]"
        You could include:
        - What does it do?
        - What is the expected behavior?
        - Where will this feature be used?
        - Who should be able to use this feature?
        - Why should this feature be added?
        - Why is this feature important?
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the use case for this feature.
      placeholder: Please provide a clear and concise description of the use case.
    validations:
      required: true
  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: Describe the benefits of this feature.
      placeholder: Please provide a clear and concise description of the benefits. How will this feature help you or others? What problems will it solve? What value will it add? What will it improve?
    validations:
      required: true
  - type: textarea
    id: drawbacks
    attributes:
      label: Drawbacks
      description: Describe any drawbacks you've considered.
      placeholder: Please provide a clear and concise description of any drawbacks you've considered.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe any alternatives you've considered.
      placeholder: Please provide a clear and concise description of any alternatives you've considered. 
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Provide any additional information or context regarding your feature request.
      placeholder: Any information that might be helpful for understanding the proposed feature.
    validations:
      required: false
  - type: textarea
    id: snippets
    attributes:
      label: Code Snippets
      description: If applicable, provide any code snippets that might be helpful. This will be automatically formatted into code, so no need for backticks.
      render: shell
      placeholder: |
        if (featureRequest) {
          console.log("Thanks for contributing to our project!");
        } else if (!featureRequest){
          console.log("Please fill out the feature request form.");
        } else {
          console.log("Something went wrong. Please try again.");
        }
        :warning: **Do not** include any sensitive information.
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What bot version is this for?
      options:
        - 0.1.0 (Initial Pre-Release)
        - 0.2.0 (Latest Pre-Release)
      default: 0
    validations:
      required: true
      multiple: true
  - type: dropdown 
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low
        - Medium
        - High
        - Critical
      default: 0
    validations:
      required: true
      multiple: false
  - type: screenshot
    id: screenshot
    attributes:
      label: Screenshot
      description: If applicable, add screenshots that support your feature request.
      placeholder: "Drag and drop a file or paste a screenshot. Accepted file types: .png, .jpg, .jpeg, .gif, .bmp, .tiff, .tif, .webp"
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: Feature Request Checklist
      description: Please check the following items before submitting your feature request.
      options:
        - label: I have searched existing feature requests to avoid creating duplicates.
        - label: My feature request is clear and well-documented.
        - label: I believe this feature would benefit a significant number of users.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct and Contributing Guidelines
      description: The Code of Conduct helps create a safe space for everyone. We require
        that everyone agrees to it. The Contributing Guidelines help us work together.
      options:
        - label: I agree to follow this project's [Code of Conduct](CODE_OF_CONDUCT.md)
        - label: I agree to follow this project's [Contributing Guidelines](CONTRIBUTING.md)
          required: true
  - type: markdown
    attributes:
      value: "Thanks for contributing to our project!"
